FROM python:3.10-slim
WORKDIR /app
COPY requirements_tagger.txt .
RUN pip install --no-cache-dir -r requirements_tagger.txt
RUN git clone https://github.com/corkborg/wd14-tagger-standalone.git wd14tagger
RUN pip install --no-cache-dir -r wd14tagger/requirements.txt
COPY tagger.py .
CMD ["celery", "-A", "tagger.celery_app", "worker", "-P", "solo", "--loglevel=info"]